version: "3"

services:
    nginx:
        image: nginx:latest
        depends_on:
            - flask
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - rose-net
        ports:
            - 80:80
    flask:
        build:
            context: /opt/srv6-pm-flask
            dockerfile: Dockerfile
        image: roseexpman:beta
        networks:
            rose-net:
                aliases:
                    - flask-app
        volumes:
            - flask-data:/usr/src/app/data
    arangodb:
        image: arangodb:latest
        environment:
            ARANGO_ROOT_PASSWORD: 12345678 # Specify your own root password.
        networks:
            rose-net:
                aliases:
                    - flask-app
        volumes:
            - arangodb:/var/lib/arangodb
        ports:
            - 8529:8529
volumes:
    flask-data:
    arangodb: