version: "3"

services:
    nginx:
        image: docker.pkg.github.com/netgroup/rose-dashboard/rose-dashboard:latest
        depends_on:
            - flask
        networks:
            rose-net:
                aliases:
                    - nginx
        ports:
            - 80:80
    flask:
        image: docker.pkg.github.com/netgroup/rose-srv6-pm-flask/rose-expman:latest
        networks:
            rose-net:
                aliases:
                    - flask-app
        volumes:
            - flask-data:/usr/src/app/data
volumes:
    flask-data:
    dashboard-data: