version: "3"

services:
    arangodb:
        image: arangodb:latest
        environment:
            ARANGO_ROOT_PASSWORD: 12345678 # Specify your own root password.
        networks:
            rose-net:
                aliases:
                    - arango-app
        volumes:
            - arangodb:/var/lib/arangodb
        ports:
            - 8529:8529
volumes:
    arangodb: