version: "3"

services:
    nginx:
        image: rose-dashboard:beta
        depends_on:
            - flask
        networks:
            rose-net:
                aliases:
                    - nginx
        ports:
            - 80:80
    flask:
        image: rose-expman:beta
        networks:
            rose-net:
                aliases:
                    - flask-app
        volumes:
            - flask-data:/usr/src/app/data
volumes:
    flask-data:
    dashboard-data: