version: "3"

services:
    nginx:
        image: rosesrv6/rose-dashboard:latest
        depends_on:
            - flask
        networks:
            rose-net:
                aliases:
                    - nginx
        ports:
            - 80:80
    flask:
        image: rosesrv6/rose-expman:latest
        networks:
            rose-net:
                aliases:
                    - flask-app
        volumes:
            - flask-data:/usr/src/app/data
volumes:
    flask-data:
    dashboard-data: